name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
        pip3 install --user --upgrade pip
        pip3 install --user --upgrade "cython<3.0.0" "setuptools<66.0.0" virtualenv buildozer

    - name: Build Android APK
      run: |
        export PATH=$PATH:$HOME/.local/bin
        buildozer android debug
      env:
        GRADLE_OPTS: "-Dorg.gradle.daemon=false"

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: bin/*.apk
        
