name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip git zip unzip openjdk-17-jdk build-essential

    - name: Install Python tools
      run: |
        pip3 install --upgrade pip
        pip3 install cython==0.29.36
        pip3 install buildozer

    - name: Check files
      run: ls -la

    - name: Build APK
      run: |
        buildozer -v android debug